#input_file: '/Users/admin/Documents/hive-results/input-1w.csv'
input_file: '/Users/admin/Development/dev-homes/stratos/burstingSim/tests/inputs/busy_time_with_gap.csv'
# input_file: '/Users/admin/Development/dev-homes/stratos/burstingSim/tests/inputs/full_clusters2.csv'
# input_file: '/Users/admin/Development/dev-homes/stratos/burstingSim/tests/inputs/busy_time_changed_from_requested.csv'

training_window: 1 #Training window size in days
start_date: '2015-05-01'
end_date: '2015-05-02'
date_filter_on: false #If false then start and end date are not considered but instead all events in file are streamed
#ignore_clusters: "drawbridge2,airpush,orchestro,wikimedia,playfirst,bd2,isec"
ignore_clusters: '' # iheartradion ignored because of null values
consider_clusters: ''

inventory_hosts_count: 10 #Number of unassigned inventory hosts per colloc
min_inventory_hosts: 3 #The minimum amount of hosts that should always be available on inventory

#Scheduler specific configuration
eviction_delay: 2 #Time needed in minutes to evict a host from a cluster to inventory
provision_delay: 2 #Time needed in minutes to provision a host from inventory to a cluster
scheduling_granularity: 60 #Time interval in minutes between scheduling decisions
policy: 'REPLAY' # REPLAY - SIMPLE
allow_provisions: true
allow_evictions: true



#Output
verbosity: v # v, vv, vvv to increase verbosity

# Obsolete Parameters
# --> Speed in trace hours/ simulation seconds. 
# Ex: 24 is for 24 trace hours per second, 1 is for 1 trace hour per simulation second
speed: 24 #XXX: Obsolete parameter. 
sim_granulatiry: 1 #XXX: Obsolete parameter. Least timer increase between simulation rounds in sec