require_relative 'update_event'

# Events generated by the YarnScheduler to replace a input_log_events
class SyntheticEvent < UpdateEvent
  # Class of events has identical content to InputLogEvent
  # Separate class created to be able to distinguish at runtime
  
end   